### ISSUE TITLE
Model Not Uploading

### ISSUE THREAD

**Issue by sramseier** [Developer-Autodesk/workflow-python-view.and.data.api#1]
Hello,

I am receiving a 404 error, however it looks like step 4 (uploading the model) is being skipped. Any help to get me on track would be greatly appreciated!
(I understand this sample is retired, however it seems to be the only resource for Python I can find).

![python vd error](https://cloud.githubusercontent.com/assets/14226255/10403589/ba4db070-6e81-11e5-8f44-ac4a0b3a1a3a.JPG)

**Comment by cyrillef** [comment]
Hi,

I fixed couple of issues in this sample - it is now uploading files properly - till I did not tested all the options. let me know if any other problem.

**Comment by sramseier** [comment]
Thanks for the quick update! Uploads occur fine now, looks like the registration/viewing is not functional, but this may have already been mentioned in the readme.

**Comment by cyrillef** [comment]
Right, did not tested this part since I was in an airport - I am back in the office now, and made teh fix as well as testing the full workflow. Should be working now. The issue was that the sample was replacing the . by a _ which is wrong since the translation pipeline needs to read the file extension. I also added code to replace spaces by the + sign which is the convention for url encoding.

**Comment by sramseier** [comment]
The full process works great now, returning a urn for viewing. Thank You!
